# Data Preprocessing Tools

## Importing the libraries

In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [41]:
dataSet = pd.read_csv('./Data.csv')
dataSet

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [42]:
# independent matrix features
# The result matrix is completely dependent on Independent Features
xMatrixFeature = dataSet.iloc[:, :-1].values
xMatrixFeature

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [43]:
# dependent matrix
# This can't be able to answer without having xMatrixFeature
yRequiredResult = dataSet.iloc[:, -1:].values
yRequiredResult

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [44]:
print(xMatrixFeature)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [45]:
print(yRequiredResult)

[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


## Taking care of missing data

In [46]:
# There are two main ways to Handle Missing data
# 1. Delete Row of Missing Data, If the dataset is big and also 1% of removing data won't hurt it
# 2. Try to fill that missing data with right value as per dataset requirement

# Always try to compute number fields of dataset is good practice to handle missing values in the
# Columns
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(xMatrixFeature[:, 1:3])
xMatrixFeature[:, 1:3] = imputer.transform(xMatrixFeature[:, 1:3])

In [47]:
print(xMatrixFeature)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [48]:
# Encode all those columns that contains categorical text
# so in This step  we will encode or map those values with numeric values to help machine
# learning model to understand the problem
# we will be using ONE HOT ENCODING for the above problem (Mapping with binary digits)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columnTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
                                      remainder='passthrough')
xMatrixFeature = np.array(columnTransformer.fit_transform(xMatrixFeature))


In [49]:
print(xMatrixFeature)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [54]:
# Here we are going to map yes or no to zero '0' and one '1'
# This will require a LabelEncoder function from sklearn Preprocessing
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
yRequiredResult = labelEncoder.fit_transform(yRequiredResult)

In [55]:
print(yRequiredResult)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

## Feature Scaling